"""
DevOps AI Agent — Ollama backend
Calls a locally or remotely running Ollama instance and returns an answer.

Direct CLI usage:
    python agent/agent.py "How do I drain a Kubernetes node?"
"""

import os
import sys
import requests
from datetime import datetime, timezone
from dotenv import load_dotenv

load_dotenv()

OLLAMA_HOST  = os.getenv("OLLAMA_HOST",  "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "mistral")

SYSTEM_PROMPT = """You are a senior DevOps and platform engineering assistant.

Your areas of expertise:
- Kubernetes: deployments, pods, services, Helm, kubectl, AKS/EKS/GKE
- CI/CD: GitHub Actions, Jenkins, Azure DevOps, pipeline design
- Cloud: Azure (AKS, ACR, Key Vault), AWS, GCP core services
- Containers: Docker, multi-stage builds, docker-compose
- IaC: Terraform, Bicep
- Linux: shell scripting, systemd, cron, log management
- Observability: Prometheus, Grafana, Azure Monitor
- Networking: ingress, DNS, TLS, service mesh basics
- Security: RBAC, secrets management, least-privilege

Response rules:
1. Lead with the direct answer — no preamble.
2. Use code blocks with correct language tags for all commands.
3. If multiple approaches exist, briefly list trade-offs.
4. Flag security concerns or common gotchas.
5. End with 2-3 related follow-up questions.
"""


def ask_ollama(question: str) -> str:
    """Send a question to Ollama and return the answer text."""

    url     = f"{OLLAMA_HOST}/api/chat"
    payload = {
        "model":  OLLAMA_MODEL,
        "stream": False,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": question},
        ],
    }

    print(f"[agent] Sending to Ollama at {OLLAMA_HOST} (model: {OLLAMA_MODEL})...")

    try:
        response = requests.post(url, json=payload, timeout=120)
        response.raise_for_status()
    except requests.exceptions.ConnectionError:
        raise SystemExit(
            f"[agent] ERROR: Cannot reach Ollama at {OLLAMA_HOST}\n"
            f"  - If running locally:  ollama serve\n"
            f"  - If on Azure VM:      check NSG port 11434 is open\n"
            f"                         sudo systemctl status ollama"
        )
    except requests.exceptions.Timeout:
        raise SystemExit(
            "[agent] ERROR: Ollama timed out after 120s.\n"
            "  Try a smaller model: ollama pull phi3"
        )
    except requests.exceptions.HTTPError as e:
        raise SystemExit(f"[agent] ERROR: Ollama returned an error: {e}")

    data = response.json()
    return data["message"]["content"]


def format_output(question: str, answer: str) -> str:
    """Wrap Q&A in a clean Markdown document."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (
        f"## DevOps Agent Answer\n\n"
        f"**Question:** {question}\n\n"
        f"---\n\n"
        f"{answer}\n\n"
        f"---\n"
        f"*Generated by Ollama ({OLLAMA_MODEL}) · {ts}*\n"
    )


def run(question: str) -> str:
    """Core entry point — returns the formatted answer and saves answer.md."""
    answer = ask_ollama(question)
    output = format_output(question, answer)

    with open("answer.md", "w", encoding="utf-8") as f:
        f.write(output)

    print("[agent] Answer saved to answer.md")
    return output


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python agent/agent.py \"your question here\"")
        sys.exit(1)

    question = " ".join(sys.argv[1:])
    print(run(question))
